//! `#[derive(Spec)]`'s write-path assembly: stitching the per-field fragments
//! into one `impl ToFields`.
//!
//! The fragments come from two siblings. The populated and template walks are
//! generated by [`populate`](super::populate), and the source walk by
//! [`source_view`](super::source_view). This module knows nothing about a
//! field's shape. It knows the shape of the impl the three walks go into, which
//! is why it sits apart from the modules that build them.

use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::Ident;

/// Assembles the field fragments into the generated `impl ToFields`: the plain
/// `to_fields` walk, the source-only `to_source_fields` walk, and the annotated
/// `to_template` walk. A struct with a doc comment also overrides `spec_doc`,
/// the fallback a parent's template walk renders above a block whose embedding
/// field has no doc.
///
/// A struct with no fields declares the item vector without `mut`, so the
/// generated impl carries no unused-mut warning under `-D warnings`.
pub(crate) fn to_fields_impl(
    name: &Ident,
    fields_emits: &[TokenStream2],
    source_emits: &[TokenStream2],
    template_emits: &[TokenStream2],
    spec_doc: &Option<String>,
) -> TokenStream2 {
    let fields_decl = items_decl(fields_emits);
    let source_decl = items_decl(source_emits);
    let template_decl = items_decl(template_emits);
    let spec_doc_impl = spec_doc.as_ref().map(|text| {
        quote! {
            fn spec_doc(&self) -> ::core::option::Option<::std::string::String> {
                ::core::option::Option::Some(#text.to_string())
            }

            fn type_doc() -> ::core::option::Option<::std::string::String> {
                ::core::option::Option::Some(#text.to_string())
            }
        }
    });
    quote! {
        impl ::confval::format::ToFields for #name {
            fn to_fields(&self) -> ::confval::format::Fields {
                #fields_decl
                #(#fields_emits)*
                ::confval::format::Fields::detached(__items)
            }

            fn to_source_fields(&self) -> ::confval::format::Fields {
                #source_decl
                #(#source_emits)*
                ::confval::format::Fields::detached(__items)
            }

            fn to_template(&self) -> ::confval::format::Fields {
                #template_decl
                #(#template_emits)*
                ::confval::format::Fields::detached(__items)
            }

            #spec_doc_impl
        }
    }
}

fn items_decl(emits: &[TokenStream2]) -> TokenStream2 {
    if emits.is_empty() {
        quote! { let __items = ::std::vec::Vec::new(); }
    } else {
        quote! { let mut __items = ::std::vec::Vec::new(); }
    }
}
