use crate::diagnostic::Report;
use crate::source::Located;

/// A closed set of allowed keyword strings, checked against a located value.
///
/// The spec layer stores keyword fields as `Located<String>` (load-balancing
/// strategies, log levels, fail policies) and validates them against a fixed
/// list, reporting at the value's span with a help line listing the options.
/// `KeywordSet` is that check, factored out so every keyword field reports
/// violations the same way, mirroring [`RangeConstraint`](super::range::RangeConstraint)
/// for numeric bounds.
///
/// The help line is always `expected one of: <comma-joined options>`. If a
/// keyword needs custom guidance instead, add a `with_help` constructor at
/// that point.
///
/// ```rust
/// use confval::prelude::{KeywordSet, Located, Report};
///
/// const STRATEGIES: [&str; 2] = ["round_robin", "least_conn"];
/// let mut report = Report::new();
/// KeywordSet::new(&STRATEGIES).check_located(
///     &Located::detached("random".to_string()),
///     "load_balancing_strategy",
///     &mut report,
/// );
/// assert!(report.has_errors());
/// ```
#[derive(Debug, Clone)]
pub struct KeywordSet<'a> {
    /// The allowed keywords, in declaration order.
    pub allowed: &'a [&'a str],
}

impl<'a> KeywordSet<'a> {
    /// A set over the given keywords.
    pub const fn new(allowed: &'a [&'a str]) -> Self {
        Self { allowed }
    }

    /// Reports `unknown {field}: {value}` unless `value` is one of the
    /// allowed keywords, with a help line of
    /// `expected one of: <comma-joined options>`.
    pub fn check_located(&self, value: &Located<String>, field: &str, report: &mut Report) {
        self.report_unknown(value, format!("unknown {field}: {}", value.value), report);
    }

    /// Reports one disallowed value with the given message and the shared
    /// options help line, unless the value is allowed.
    fn report_unknown(&self, value: &Located<String>, message: String, report: &mut Report) {
        if self.allowed.contains(&value.value.as_str()) {
            return;
        }
        report
            .error(message)
            .at(value.span)
            .help(format!("expected one of: {}", self.allowed.join(", ")))
            .emit();
    }

    /// Checks every value in a list field, reporting each bad element at its
    /// own span through [`check_located`](KeywordSet::check_located).
    ///
    /// `field` names one element rather than the list, so a list of events
    /// reports `unknown event: reloded` and points at the element the
    /// operator typed. An empty list and an all-valid list report nothing.
    ///
    /// Both list shapes pass a slice. A bare
    /// `Vec<Located<String>>` passes itself, and a wrapped
    /// `Option<Located<Vec<Located<String>>>>` passes `&list.value`.
    pub fn check_each(&self, values: &[Located<String>], field: &str, report: &mut Report) {
        for value in values {
            self.check_located(value, field, report);
        }
    }

    /// Reports `unknown value in {field}: {value}` for every disallowed
    /// element, each at its own span.
    ///
    /// The message names the list, which reads correctly
    /// whatever the field is called. A list field is conventionally plural, so
    /// `check_each` would report `unknown modes: nope` for a field named
    /// `modes`. Use [`check_each`](KeywordSet::check_each) instead when you have
    /// a singular noun for one element, because `unknown mode: nope` is the
    /// shorter sentence.
    ///
    /// This is the form `#[confval(keywords = ...)]` generates for a list, where
    /// the derive knows the field name and not the name of one element.
    pub fn check_each_in(&self, values: &[Located<String>], field: &str, report: &mut Report) {
        for value in values {
            self.report_unknown(
                value,
                format!("unknown value in {field}: {}", value.value),
                report,
            );
        }
    }
}

/// Whether every keyword in the slice is distinct. Generated by
/// [`keyword_enum!`] as a compile-time assertion, so a table that maps two
/// variants to one keyword is rejected rather than leaving a `TryFrom` that
/// can never return the second variant.
#[doc(hidden)]
pub const fn __keyword_enum_keywords_unique(keywords: &[&str]) -> bool {
    let mut i = 0;
    while i < keywords.len() {
        let mut j = i + 1;
        while j < keywords.len() {
            if const_bytes_eq(keywords[i].as_bytes(), keywords[j].as_bytes()) {
                return false;
            }
            j += 1;
        }
        i += 1;
    }
    true
}

const fn const_bytes_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut index = 0;
    while index < a.len() {
        if a[index] != b[index] {
            return false;
        }
        index += 1;
    }
    true
}

/// Declare a keyword enum, its allowed set, and the conversions between them in
/// one place.
///
/// A closed-set field is otherwise declared three times. A `const` slice of
/// allowed strings feeds the `KeywordSet` check. A runtime enum holds the value
/// the program runs on. A `TryFrom<&str>` bridges the two at lowering. Nothing
/// keeps the three in agreement, so a variant added to one and not the others
/// drifts. `keyword_enum!` generates all three from a single table, plus
/// `as_str` and `Display` for printing a variant back to its keyword.
///
/// For the visibility you give it, the macro generates:
///
/// - the enum, deriving `Debug, Clone, Copy, PartialEq, Eq`,
/// - `KEYWORDS`, the allowed strings in declaration order,
/// - `keyword_set()`, a `KeywordSet` over `KEYWORDS` to call from a `Validate` impl,
/// - `as_str`, the keyword for a variant,
/// - `TryFrom<&str>`, accepting exactly the keywords,
/// - `Display`, printing through `as_str`,
/// - `serde::Serialize` writing the keyword string, when confval's `serde`
///   feature is enabled, so a serialized config carries `"log"` exactly as the
///   config file does.
///
/// The macro does not run the check. On a derived spec, record the set on the
/// field with `#[confval(keywords = LimitMode)]`, and the derive runs the
/// `keyword_set().check_located(...)` call during validation. On a handwritten
/// spec, call it in your `Validate` impl. Either way, a value that fails the
/// check never reaches the `TryFrom`, so the enum and its set cannot drift.
///
/// A table that maps two variants to one keyword is a compile error, because
/// its `TryFrom` could never return the second variant.
///
/// Attributes before the visibility apply to the enum, and attributes before a
/// variant apply to that variant, so you can document both and use the macro in
/// a crate that denies `missing_docs`. The generated items carry their own
/// docs.
///
/// ```rust
/// use confval::keyword_enum;
///
/// keyword_enum!(LimitMode, {
///     Enforce => "enforce",
///     Log     => "log",
///     Off     => "off",
/// });
///
/// assert_eq!(LimitMode::KEYWORDS, ["enforce", "log", "off"]);
/// assert_eq!(LimitMode::Log.as_str(), "log");
/// assert_eq!(LimitMode::try_from("off"), Ok(LimitMode::Off));
/// assert!(LimitMode::try_from("nope").is_err());
/// ```
#[macro_export]
macro_rules! keyword_enum {
    (
        $(#[$meta:meta])* $vis:vis $name:ident,
        { $($(#[$variant_meta:meta])* $variant:ident => $kw:literal),+ $(,)? }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        $vis enum $name {
            $($(#[$variant_meta])* $variant,)+
        }

        const _: () = ::core::assert!(
            $crate::pipeline::keyword::__keyword_enum_keywords_unique(&[$($kw,)+]),
            "keyword_enum!: two variants map to the same keyword"
        );

        impl $name {
            /// The allowed keyword strings, in declaration order.
            $vis const KEYWORDS: [&'static str; $crate::keyword_enum!(@count $($variant)+)] =
                [$($kw,)+];

            /// The keyword for this variant.
            $vis const fn as_str(&self) -> &'static str {
                match self {
                    $(Self::$variant => $kw,)+
                }
            }

            /// A `KeywordSet` over `KEYWORDS`, for a `Validate` impl to check a
            /// located value against.
            $vis fn keyword_set() -> $crate::KeywordSet<'static> {
                $crate::KeywordSet::new(&Self::KEYWORDS)
            }
        }

        impl ::core::convert::TryFrom<&str> for $name {
            type Error = ();

            fn try_from(value: &str) -> ::core::result::Result<Self, ()> {
                match value {
                    $($kw => ::core::result::Result::Ok(Self::$variant),)+
                    _ => ::core::result::Result::Err(()),
                }
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        $crate::__keyword_enum_serde!($name);
    };
    (@count) => { 0usize };
    (@count $head:ident $($tail:ident)*) => {
        1usize + $crate::keyword_enum!(@count $($tail)*)
    };
}

/// The serde half of [`keyword_enum!`], expanded through `$crate` so the
/// condition is confval's own `serde` feature rather than the caller's.
/// Serialization writes the keyword string, mirroring `Display`. There is no
/// `Deserialize`, because parsing owns the read path.
#[cfg(feature = "serde")]
#[doc(hidden)]
#[macro_export]
macro_rules! __keyword_enum_serde {
    ($name:ident) => {
        impl $crate::__private::serde::Serialize for $name {
            fn serialize<S: $crate::__private::serde::Serializer>(
                &self,
                serializer: S,
            ) -> ::core::result::Result<S::Ok, S::Error> {
                serializer.serialize_str(self.as_str())
            }
        }
    };
}

#[cfg(not(feature = "serde"))]
#[doc(hidden)]
#[macro_export]
macro_rules! __keyword_enum_serde {
    ($name:ident) => {};
}

#[cfg(test)]
mod tests {
    use super::*;

    const COLORS: [&str; 3] = ["red", "green", "blue"];

    fn check(value: &str, field: &'static str) -> Report {
        let mut report = Report::new();
        KeywordSet::new(&COLORS).check_located(
            &Located::detached(value.to_string()),
            field,
            &mut report,
        );
        report
    }

    #[test]
    fn allowed_keyword_reports_nothing() {
        assert!(!check("red", "color").has_issues());
        assert!(!check("blue", "color").has_issues());
    }

    #[test]
    fn unknown_keyword_reports_with_field_and_value() {
        let report = check("purple", "color");
        assert!(report.has_errors());
        assert_eq!(report.issues()[0].message, "unknown color: purple");
    }

    #[test]
    fn default_help_lists_options() {
        let report = check("purple", "color");
        assert_eq!(
            report.issues()[0].help.as_deref(),
            Some("expected one of: red, green, blue")
        );
    }

    #[test]
    fn check_each_reports_one_error_per_bad_element() {
        // Arrange
        let values = vec![
            Located::detached("red".to_string()),
            Located::detached("purple".to_string()),
            Located::detached("mauve".to_string()),
        ];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each(&values, "color", &mut report);

        // Assert
        let messages: Vec<&str> = report
            .issues()
            .iter()
            .map(|issue| issue.message.as_str())
            .collect();
        assert_eq!(
            messages,
            vec!["unknown color: purple", "unknown color: mauve"]
        );
    }

    #[test]
    fn check_each_reports_nothing_for_a_clean_list() {
        // Arrange
        let values = vec![
            Located::detached("red".to_string()),
            Located::detached("blue".to_string()),
        ];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each(&values, "color", &mut report);

        // Assert
        assert!(!report.has_issues());
    }

    #[test]
    fn check_each_in_names_the_field_rather_than_one_element() {
        // Arrange
        let values = vec![
            Located::detached("red".to_string()),
            Located::detached("purple".to_string()),
        ];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each_in(&values, "colors", &mut report);

        // Assert
        // The plural field name reads correctly because the message names the
        // field it sits in rather than one element of it.
        assert_eq!(report.issues().len(), 1);
        assert_eq!(
            report.issues()[0].message,
            "unknown value in colors: purple"
        );
        assert_eq!(
            report.issues()[0].help.as_deref(),
            Some("expected one of: red, green, blue")
        );
    }

    #[test]
    fn check_each_in_carries_each_element_span() {
        // Arrange
        let mut sources = crate::source::SourceMap::new();
        let id = sources.add("test.hcl", "colors = [\"purple\"]");
        let span = crate::source::Span {
            source: id,
            start: 11,
            end: 17,
        };
        let values = vec![Located {
            value: "purple".to_string(),
            span,
        }];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each_in(&values, "colors", &mut report);

        // Assert
        assert_eq!(report.issues()[0].span, Some(span));
    }

    #[test]
    fn check_each_keeps_its_singular_wording_for_a_handwritten_caller() {
        // Arrange
        let values = vec![Located::detached("purple".to_string())];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each(&values, "color", &mut report);

        // Assert
        assert_eq!(report.issues()[0].message, "unknown color: purple");
    }

    #[test]
    fn check_each_reports_nothing_for_an_empty_list() {
        // Arrange
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each(&[], "color", &mut report);

        // Assert
        assert!(!report.has_issues());
    }

    #[test]
    fn check_each_carries_each_element_span() {
        // Arrange
        let mut sources = crate::source::SourceMap::new();
        let id = sources.add("test.hcl", "colors = [\"purple\"]");
        let span = crate::source::Span {
            source: id,
            start: 11,
            end: 17,
        };
        let values = vec![Located {
            value: "purple".to_string(),
            span,
        }];
        let mut report = Report::new();

        // Act
        KeywordSet::new(&COLORS).check_each(&values, "color", &mut report);

        // Assert
        assert_eq!(report.issues()[0].span, Some(span));
    }

    #[test]
    fn error_carries_the_value_span() {
        let mut sources = crate::source::SourceMap::new();
        let id = sources.add("test.hcl", "color = \"purple\"");
        let span = crate::source::Span {
            source: id,
            start: 9,
            end: 15,
        };
        let mut report = Report::new();
        KeywordSet::new(&COLORS).check_located(
            &Located {
                value: "purple".to_string(),
                span,
            },
            "color",
            &mut report,
        );
        assert_eq!(report.issues()[0].span, Some(span));
    }

    keyword_enum!(LimitMode, {
        Enforce => "enforce",
        Log     => "log",
        Off     => "off",
    });

    keyword_enum!(Single, {
        Only => "only",
    });

    keyword_enum!(
        /// The failure handling mode, documented.
        #[allow(dead_code)]
        pub Documented, {
            /// Failures stop the run.
            Strict => "strict",
            /// Failures are logged and skipped.
            Lenient => "lenient",
        }
    );

    #[test]
    fn attributes_pass_through_to_the_enum_and_variants() {
        // Assert
        // The declaration above compiles with a doc comment and an attribute on
        // the enum and a doc comment on each variant, and behaves normally.
        assert_eq!(Documented::KEYWORDS, ["strict", "lenient"]);
        assert_eq!(Documented::try_from("lenient"), Ok(Documented::Lenient));
        assert_eq!(Documented::keyword_set().allowed, Documented::KEYWORDS);
    }

    #[test]
    fn keywords_hold_the_set_in_declaration_order() {
        // Assert
        assert_eq!(LimitMode::KEYWORDS, ["enforce", "log", "off"]);
    }

    #[test]
    fn as_str_returns_the_keyword_for_each_variant() {
        // Assert
        assert_eq!(LimitMode::Enforce.as_str(), "enforce");
        assert_eq!(LimitMode::Log.as_str(), "log");
        assert_eq!(LimitMode::Off.as_str(), "off");
    }

    #[test]
    fn try_from_accepts_every_keyword() {
        // Assert
        assert_eq!(LimitMode::try_from("enforce"), Ok(LimitMode::Enforce));
        assert_eq!(LimitMode::try_from("log"), Ok(LimitMode::Log));
        assert_eq!(LimitMode::try_from("off"), Ok(LimitMode::Off));
    }

    #[test]
    fn try_from_rejects_a_string_outside_the_set() {
        // Assert
        assert!(LimitMode::try_from("warn").is_err());
    }

    #[test]
    fn display_prints_the_keyword() {
        // Assert
        assert_eq!(LimitMode::Off.to_string(), "off");
    }

    #[test]
    fn keyword_set_accepts_an_allowed_value() {
        // Arrange
        let mut report = Report::new();

        // Act
        LimitMode::keyword_set().check_located(
            &Located::detached("log".to_string()),
            "mode",
            &mut report,
        );

        // Assert
        assert!(!report.has_issues());
    }

    #[test]
    fn keyword_set_reports_an_unknown_value() {
        // Arrange
        let mut report = Report::new();

        // Act
        LimitMode::keyword_set().check_located(
            &Located::detached("warn".to_string()),
            "mode",
            &mut report,
        );

        // Assert
        assert!(report.has_errors());
    }

    #[test]
    fn every_variant_round_trips_through_its_keyword() {
        // Assert
        for (variant, keyword) in [
            (LimitMode::Enforce, "enforce"),
            (LimitMode::Log, "log"),
            (LimitMode::Off, "off"),
        ] {
            assert_eq!(variant.as_str(), keyword);
            assert_eq!(LimitMode::try_from(keyword), Ok(variant));
        }
    }

    #[cfg(feature = "serde")]
    #[test]
    fn serialize_writes_the_keyword_not_the_variant_name() {
        // Act
        let json = serde_json::to_string(&LimitMode::Log).unwrap();

        // Assert
        assert_eq!(json, "\"log\"");
    }

    #[test]
    fn single_variant_table_with_trailing_comma_expands() {
        // Assert
        assert_eq!(Single::KEYWORDS, ["only"]);
        assert_eq!(Single::Only.as_str(), "only");
        assert_eq!(Single::Only.to_string(), "only");
        assert_eq!(Single::keyword_set().allowed.len(), 1);
        assert_eq!(Single::try_from("only"), Ok(Single::Only));
    }

    #[test]
    fn keywords_unique_returns_true_for_a_distinct_set() {
        // Act
        let unique = __keyword_enum_keywords_unique(&["ab", "ac", "ad"]);

        // Assert
        assert!(unique);
    }

    #[test]
    fn keywords_unique_returns_false_for_a_duplicate() {
        // Act
        let unique = __keyword_enum_keywords_unique(&["ab", "cd", "ab"]);

        // Assert
        assert!(!unique);
    }

    #[test]
    fn keywords_unique_treats_different_lengths_as_distinct() {
        // Act
        let unique = __keyword_enum_keywords_unique(&["a", "bb"]);

        // Assert
        assert!(unique);
    }

    #[test]
    fn keywords_unique_returns_true_for_an_empty_set() {
        // Act
        let unique = __keyword_enum_keywords_unique(&[]);

        // Assert
        assert!(unique);
    }
}
